version: "3"

vars:
  RTMP_ADDR: 127.0.0.1:1935/ada/instance
  TEST_FILE: tests/resources/test.mp4

tasks:
  run:
    cmd: cargo run
    env:
      RUST_BACKTRACE: 1
      RUST_LIB_BACKTRACE: 1

  ffmpeg:
    cmd: |
      ffmpeg \
        -loglevel debug \
        -stream_loop -1 \
        -i {{ .TEST_FILE }} \
        -c copy \
        -f flv \
        "rtmp://{{ .RTMP_ADDR }} chunk_size=4096"

  # -c:v libx264 -c:a aac
  # -c copy
